/**
 * Recurring template extras: expense doc type + auto-enter vs remind-only.
 *
 *  - docType 'expense' delegates to createExpense and posts a balanced entry.
 *  - autoEnter=false templates are NOT generated by runDue; they come back as
 *    reminders and keep their nextRunDate until run explicitly.
 *  - runTemplateNow posts a remind-only template and advances its schedule.
 *  - The __options key stored in the template jsonb is stripped before the
 *    payload reaches the create services.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import path from 'node:path';
import fs from 'node:fs';
import { eq } from 'drizzle-orm';
import { getDb, closeDb, type DB } from '@/lib/db';
import { users, companies, vendors, expenses, bills, recurringTemplates } from '@/lib/db/schema';
import type { ServiceContext } from './_base';
import { createAccount } from './accounts';
import { trialBalance } from './reports';
import {
  createTemplate,
  getTemplate,
  runDue,
  runTemplateNow,
  templateAutoEnter,
} from './recurring';

const TEST_DIR = path.resolve(process.cwd(), '.bookkeeper-data', 'test-recurring-extras');
let ctx: ServiceContext;
let db: DB;
const acct: Record<string, string> = {};
let vendorId: string;

describe('Recurring templates — expense docType + auto-enter modes', () => {
  beforeAll(async () => {
    db = await getDb(TEST_DIR);

    const [user] = await db
      .insert(users)
      .values({ email: 'recurring-extras@test.local', name: 'Extras Owner', passwordHash: 'x' })
      .returning();
    const [company] = await db
      .insert(companies)
      .values({ name: 'Recurring Extras Co', ownerId: user.id })
      .returning();
    ctx = { db, companyId: company.id, userId: user.id };

    const defs: Array<[string, string, string, string]> = [
      ['1000', 'Checking', 'asset', 'checking'],
      ['2000', 'Accounts Payable', 'liability', 'accounts_payable'],
      ['6300', 'Office Supplies', 'expense', 'operating_expenses'],
      ['6400', 'Utilities', 'expense', 'operating_expenses'],
    ];
    for (const [code, name, type, subtype] of defs) {
      const row = await createAccount(ctx, { code, name, type: type as never, subtype });
      acct[code] = row.id;
    }

    const [vendor] = await db
      .insert(vendors)
      .values({ companyId: company.id, displayName: 'Recurring Vendor' })
      .returning();
    vendorId = vendor.id;
  });

  afterAll(async () => {
    await closeDb(TEST_DIR);
    fs.rmSync(TEST_DIR, { recursive: true, force: true });
  });

  // -----------------------------------------------------------------------
  // Expense templates
  // -----------------------------------------------------------------------

  it('generates an expense from an expense template via runTemplateNow', async () => {
    const tpl = await createTemplate(ctx, {
      name: 'Monthly Utilities',
      docType: 'expense',
      frequency: 'monthly',
      // Future-dated so runDue in later tests does not also fire it.
      nextRunDate: new Date(Date.now() + 30 * 24 * 3600 * 1000),
      template: {
        vendorId,
        method: 'cash',
        paymentAccountId: acct['1000'],
        lines: [{ accountId: acct['6400'], description: 'Electric', amount: '45.00' }],
      },
    });

    const doc = await runTemplateNow(ctx, tpl.id);
    expect(doc.docType).toBe('expense');

    const [expense] = await db.select().from(expenses).where(eq(expenses.id, doc.docId));
    expect(expense).toBeTruthy();
    expect(expense.total).toBe('45.00');
    expect(expense.vendorId).toBe(vendorId);

    const tb = await trialBalance(ctx);
    expect(tb.balanced).toBe(true);
  });

  // -----------------------------------------------------------------------
  // Auto-enter vs remind-only
  // -----------------------------------------------------------------------

  it('stores the auto-enter option in the template jsonb (default true)', async () => {
    const auto = await createTemplate(ctx, {
      name: 'Auto Bill',
      docType: 'bill',
      frequency: 'monthly',
      nextRunDate: new Date('2026-01-05'),
      template: {
        vendorId,
        lines: [{ accountId: acct['6300'], description: 'Supplies', amount: '25.00' }],
      },
    });
    expect(templateAutoEnter(auto.template as Record<string, unknown>)).toBe(true);

    const remind = await createTemplate(ctx, {
      name: 'Remind Bill',
      docType: 'bill',
      frequency: 'monthly',
      nextRunDate: new Date('2026-01-05'),
      autoEnter: false,
      template: {
        vendorId,
        lines: [{ accountId: acct['6300'], description: 'Rent-ish', amount: '500.00' }],
      },
    });
    expect(templateAutoEnter(remind.template as Record<string, unknown>)).toBe(false);
  });

  it('runDue posts auto-enter templates but only reports remind-only ones', async () => {
    const asOf = new Date('2026-01-10');
    const { generated, reminders } = await runDue(ctx, asOf);

    // The auto template generated a bill; the remind-only one did not.
    expect(generated.length).toBe(1);
    expect(generated[0].templateName).toBe('Auto Bill');
    expect(reminders.length).toBe(1);
    expect(reminders[0].templateName).toBe('Remind Bill');

    // The generated bill exists with the right total and a clean payload
    // (the __options key must NOT leak into createBill).
    const [bill] = await db.select().from(bills).where(eq(bills.id, generated[0].docId));
    expect(bill.total).toBe('25.00');

    // Remind-only template keeps its nextRunDate (still due next run).
    const [remindRow] = await db
      .select()
      .from(recurringTemplates)
      .where(eq(recurringTemplates.id, reminders[0].templateId));
    expect(new Date(remindRow.nextRunDate!).toISOString().slice(0, 10)).toBe('2026-01-05');

    // Auto template advanced past asOf.
    const autoRow = await getTemplate(ctx, generated[0].templateId);
    expect(new Date(autoRow.nextRunDate!).getTime()).toBeGreaterThan(asOf.getTime());

    const tb = await trialBalance(ctx);
    expect(tb.balanced).toBe(true);
  });

  it('runDue keeps reminding until the template is run explicitly', async () => {
    // Second run: still a reminder, still nothing generated for it.
    const second = await runDue(ctx, new Date('2026-01-11'));
    expect(second.generated.length).toBe(0);
    expect(second.reminders.length).toBe(1);
    const reminder = second.reminders[0];

    // User posts it explicitly.
    const doc = await runTemplateNow(ctx, reminder.templateId);
    const [bill] = await db.select().from(bills).where(eq(bills.id, doc.docId));
    expect(bill.total).toBe('500.00');

    // Schedule advanced — no longer due, no more reminders.
    const third = await runDue(ctx, new Date('2026-01-12'));
    expect(third.generated.length).toBe(0);
    expect(third.reminders.length).toBe(0);

    const tb = await trialBalance(ctx);
    expect(tb.balanced).toBe(true);
  });

  it('rejects unknown doc types', async () => {
    await expect(
      createTemplate(ctx, {
        name: 'Bad',
        docType: 'purchase_order' as never,
        frequency: 'monthly',
        nextRunDate: new Date(),
        template: {},
      }),
    ).rejects.toMatchObject({ code: 'VALIDATION' });
  });
});
